/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LLIST_H_RPCGEN
#define _LLIST_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


enum color {
	ORANGE = 0,
	PUCE = 1,
	TURQUOISE = 2,
};
typedef enum color color;
#ifdef __cplusplus
extern "C" bool_t xdr_color(XDR *, color*);
#elif __STDC__
extern  bool_t xdr_color(XDR *, color*);
#else /* Old Style C */
bool_t xdr_color();
#endif /* Old Style C */


struct list {
	char *data;
	int key;
	color col;
	struct list *next;
};
typedef struct list list;
#ifdef __cplusplus
extern "C" bool_t xdr_list(XDR *, list*);
#elif __STDC__
extern  bool_t xdr_list(XDR *, list*);
#else /* Old Style C */
bool_t xdr_list();
#endif /* Old Style C */


#define PRINTER ((rpc_uint)0x2fffffff)
#define PRINTER_V1 ((rpc_uint)1)

#ifdef __cplusplus
#define PRINT_LIST ((rpc_uint)1)
extern "C" int * print_list_1(list *, CLIENT *);
extern "C" int * print_list_1_svc(list *, struct svc_req *);
#define SUM_LIST ((rpc_uint)2)
extern "C" int * sum_list_1(list *, CLIENT *);
extern "C" int * sum_list_1_svc(list *, struct svc_req *);

#elif __STDC__
#define PRINT_LIST ((rpc_uint)1)
extern  int * print_list_1(list *, CLIENT *);
extern  int * print_list_1_svc(list *, struct svc_req *);
#define SUM_LIST ((rpc_uint)2)
extern  int * sum_list_1(list *, CLIENT *);
extern  int * sum_list_1_svc(list *, struct svc_req *);

#else /* Old Style C */
#define PRINT_LIST ((rpc_uint)1)
extern  int * print_list_1();
extern  int * print_list_1_svc();
#define SUM_LIST ((rpc_uint)2)
extern  int * sum_list_1();
extern  int * sum_list_1_svc();
#endif /* Old Style C */

#endif /* !_LLIST_H_RPCGEN */
